### ISSUE TITLE
Support de python 3.5 ?

### ISSUE THREAD

**Issue by lhirlimann** [3liz/qgis-plugin-manager#5]
J'ai des clients en stretch - qui sont pas près de passer en buster. On peut reduire le requirement à python 3.5 ?

**Comment by Gustry** [comment]
There is indeed a few functions from the Path library not available in Python 3.5 in the current implementation.

I would need to have a look manually in the code and update the code.

**Comment by lhirlimann** [comment]
If it's too much work, don't bother.

**Comment by dmarteau** [comment]
It is straightforward to install another version side by side the default version:

As an exemple here ansible tasks for installing python 3.8:
```
#
# Install python 3.8
#

- name: Add python ppa
  apt_repository: repo=ppa:deadsnakes/ppa

- name: Install python 3.8
  apt: 
    name: "{{ packages }}"
    install_recommends: no
  vars: 
    packages:
      - python3.8
      - python3.8-venv
      - python3.8-dev

``` 

From this, you may install anything you want in **venv**.
